[package]
name = "rewr"
version = "0.0.0"
authors = ["avitex <avitex@wfxlabs.com>"]
edition = "2018"

[dependencies]
memchr = "2"
jetscii = "0.5"
dangerous = { git = "https://github.com/avitex/rust-dangerous", branch = "master" }
